package org.es4j.persistence.sql.SqlDialects;


//namespace EventStore.Persistence.SqlPersistence.SqlDialects {
//using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    //[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    //[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class SqliteStatements {
/*
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqliteStatements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventStore.Persistence.SqlPersistence.SqlDialects.SqliteStatements", typeof(SqliteStatements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
*/        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS Commits
        ///(
        ///       StreamId guid NOT NULL,
        ///       StreamRevision int NOT NULL CHECK (StreamRevision &gt; 0),
        ///       Items int NOT NULL CHECK (Items &gt; 0),
        ///       CommitId guid NOT NULL CHECK (CommitId != 0),
        ///       CommitSequence int NOT NULL CHECK (CommitSequence &gt; 0),
        ///       CommitStamp datetime NOT NULL,
        ///       Dispatched bit NOT NULL DEFAULT 0,
        ///       Headers blob NULL,
        ///       Payload blob NOT NULL,
        ///       CONSTRAINT PK_Commits PRIMARY KEY (StreamId, CommitSequence)
        ///);
        /// [rest of string was truncated]&quot;;.
        /// </summary>
    public static String initializeStorage() {

        //return null; // ResourceManager.GetString("InitializeStorage", resourceCulture);
return 
"CREATE TABLE IF NOT EXISTS Commits\n" +
"(\n" +
"       StreamId guid NOT NULL,\n" +
"       StreamRevision int NOT NULL CHECK (StreamRevision &gt; 0),\n" +
"       Items int NOT NULL CHECK (Items &gt; 0),\n" +
"       CommitId guid NOT NULL CHECK (CommitId != 0),\n" +
"       CommitSequence int NOT NULL CHECK (CommitSequence &gt; 0),\n" +
"       CommitStamp datetime NOT NULL,\n" +
"       Dispatched bit NOT NULL DEFAULT 0,\n" +
"       Headers blob NULL,\n" +
"       Payload blob NOT NULL,\n" +
"       CONSTRAINT PK_Commits PRIMARY KEY (StreamId, CommitSequence)\n" +
");\n" +
"CREATE UNIQUE INDEX IF NOT EXISTS IX_Commits_CommitId ON Commits (StreamId, CommitId);\n" +
"CREATE UNIQUE INDEX IF NOT EXISTS IX_Commits_Revisions ON Commits (StreamId, StreamRevision, Items);\n" +
"CREATE INDEX IF NOT EXISTS IX_Commits_Dispatched ON Commits (Dispatched);\n" +
"CREATE INDEX IF NOT EXISTS IX_Commits_Stamp ON Commits (CommitStamp);\n" +
" \n" +
"CREATE TABLE IF NOT EXISTS Snapshots\n" +
"(\n" +
"       StreamId guid NOT NULL,\n" +
"       StreamRevision int NOT NULL CHECK (StreamRevision &gt; 0),\n" +
"       Payload blob NOT NULL,\n" +
"       CONSTRAINT PK_Snapshots PRIMARY KEY (StreamId, StreamRevision)\n" +
");";
    }
}



/*
﻿<?xml version="1.0" encoding="utf-8"?>
<root>
  <!-- 
    Microsoft ResX Schema 
    
    Version 2.0
    
    The primary goals of this format is to allow a simple XML format 
    that is mostly human readable. The generation and parsing of the 
    various data types are done through the TypeConverter classes 
    associated with the data types.
    
    Example:
    
    ... ado.net/XML headers & schema ...
    <resheader name="resmimetype">text/microsoft-resx</resheader>
    <resheader name="version">2.0</resheader>
    <resheader name="reader">System.Resources.ResXResourceReader, System.Windows.Forms, ...</resheader>
    <resheader name="writer">System.Resources.ResXResourceWriter, System.Windows.Forms, ...</resheader>
    <data name="Name1"><value>this is my long string</value><comment>this is a comment</comment></data>
    <data name="Color1" type="System.Drawing.Color, System.Drawing">Blue</data>
    <data name="Bitmap1" mimetype="application/x-microsoft.net.object.binary.base64">
        <value>[base64 mime encoded serialized .NET Framework object]</value>
    </data>
    <data name="Icon1" type="System.Drawing.Icon, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
        <value>[base64 mime encoded string representing a byte array form of the .NET Framework object]</value>
        <comment>This is a comment</comment>
    </data>
                
    There are any number of "resheader" rows that contain simple 
    name/value pairs.
    
    Each data row contains a name, and value. The row also contains a 
    type or mimetype. Type corresponds to a .NET class that support 
    text/value conversion through the TypeConverter architecture. 
    Classes that don't support this are serialized and stored with the 
    mimetype set.
    
    The mimetype is used for serialized objects, and tells the 
    ResXResourceReader how to depersist the object. This is currently not 
    extensible. For a given mimetype the value must be set accordingly:
    
    Note - application/x-microsoft.net.object.binary.base64 is the format 
    that the ResXResourceWriter will generate, however the reader can 
    read any of the formats listed below.
    
    mimetype: application/x-microsoft.net.object.binary.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
            : and then encoded with base64 encoding.
    
    mimetype: application/x-microsoft.net.object.soap.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Soap.SoapFormatter
            : and then encoded with base64 encoding.

    mimetype: application/x-microsoft.net.object.bytearray.base64
    value   : The object must be serialized into a byte array 
            : using a System.ComponentModel.TypeConverter
            : and then encoded with base64 encoding.
    -->
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" />
              </xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string" />
              <xsd:attribute name="name" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <data name="InitializeStorage" xml:space="preserve">
    <value>CREATE TABLE IF NOT EXISTS Commits
(
       StreamId guid NOT NULL,
       StreamRevision int NOT NULL CHECK (StreamRevision &gt; 0),
       Items int NOT NULL CHECK (Items &gt; 0),
       CommitId guid NOT NULL CHECK (CommitId != 0),
       CommitSequence int NOT NULL CHECK (CommitSequence &gt; 0),
       CommitStamp datetime NOT NULL,
       Dispatched bit NOT NULL DEFAULT 0,
       Headers blob NULL,
       Payload blob NOT NULL,
       CONSTRAINT PK_Commits PRIMARY KEY (StreamId, CommitSequence)
);
CREATE UNIQUE INDEX IF NOT EXISTS IX_Commits_CommitId ON Commits (StreamId, CommitId);
CREATE UNIQUE INDEX IF NOT EXISTS IX_Commits_Revisions ON Commits (StreamId, StreamRevision, Items);
CREATE INDEX IF NOT EXISTS IX_Commits_Dispatched ON Commits (Dispatched);
CREATE INDEX IF NOT EXISTS IX_Commits_Stamp ON Commits (CommitStamp);

CREATE TABLE IF NOT EXISTS Snapshots
(
       StreamId guid NOT NULL,
       StreamRevision int NOT NULL CHECK (StreamRevision &gt; 0),
       Payload blob NOT NULL,
       CONSTRAINT PK_Snapshots PRIMARY KEY (StreamId, StreamRevision)
);</value>
  </data>
</root>
*/