package org.es4j.persistence.sql;

//------------------------------------------------------------------------------

import org.es4j.util.CultureInfo;
import org.es4j.util.ResourceManager;

// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    //[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    //[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    class Messages {
        
        private static ResourceManager resourceMan;
        private static CultureInfo     resourceCulture;
        
        //[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        private Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        //[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private static ResourceManager getResourceManager() {
            if (resourceMan == null) {
                    ResourceManager temp = new ResourceManager("EventStore.Persistence.SqlPersistence.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        //[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private static CultureInfo getCulture() {
                return resourceCulture;
        }
        private static void setCulture(CultureInfo resourceCulture_) {
            resourceCulture = resourceCulture_;
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding parameter named &apos;{0}&apos; to statement..
        /// </summary>
        public static String addingParameter() {
                return ResourceManager.getString("AddingParameter", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding snapshot to stream &apos;{0}&apos; at position {1}..
        /// </summary>
        public static String AddingSnapshot {
            return ResourceManager.getString("AddingSnapshot", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to use storage after it has been disposed..
        /// </summary>
        public static String alreadyDisposed() {
            get {
                return ResourceManager.getString("AlreadyDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to commit {0} events on stream &apos;{1}&apos; at sequence {2}..
        /// </summary>
        public static String attemptingToCommit() {
            get {
                return ResourceManager.getString("AttemptingToCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection could not be created for the specified named connection..
        /// </summary>
        public static String badConnectionName() {
            get {
                return ResourceManager.getString("BadConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The factory provided was unable to create an object to store..
        /// </summary>
        public static String badFactoryResult() {
            get {
                return ResourceManager.getString("BadFactoryResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding parameter &apos;{0}&apos; with value: {1}.
        /// </summary>
        public static String bBindingParameter() {
            get {
                return ResourceManager.getString("BindingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning up root threaded scope.
        /// </summary>
        public static String cleaningRootThreadScope() {
            get {
                return ResourceManager.getString("CleaningRootThreadScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command has client-controlled transaction: {0}..
        /// </summary>
        public static String clientControlledTransaction() {
            get {
                return ResourceManager.getString("ClientControlledTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command executed, {0} rows affected..
        /// </summary>
        public static String commandExecuted() {
            get {
                return ResourceManager.getString("CommandExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command text to be executed: {0}.
        /// </summary>
        public static String commandTextToExecute() {
            get {
                return ResourceManager.getString("CommandTextToExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-query statement threw an exception of type &apos;{0}&apos;..
        /// </summary>
        public static String commandThrewException() {
            get {
                return ResourceManager.getString("CommandThrewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit &apos;{0}&apos; persisted successfully..
        /// </summary>
        public static String commitPersisted() {
            get {
                return ResourceManager.getString("CommitPersisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurrent write detected..
        /// </summary>
        public static String ConcurrentWriteDetected {
            get {
                return ResourceManager.getString("ConcurrentWriteDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring connections: master &apos;{0}&apos;; replica &apos;{1}&apos;, shards: {2}..
        /// </summary>
        public static String configuringConnections() {
            return ResourceManager.getString("ConfiguringConnections", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find connection name &apos;{0}&apos; in the configuration file..
        /// </summary>
        public static String connectionNotFound() {
            return ResourceManager.getString("ConnectionNotFound", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating command..
        /// </summary>
        public static String creatingCommand() {
            
                return ResourceManager.getString("CreatingCommand", resourceCulture);
            
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserializing commit from record using serializer of type &apos;{0}&apos;..
        /// </summary>
        public static String deserializingCommit() {
            
                return ResourceManager.getString("DeserializingCommit", resourceCulture);
            
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserializing snapshot from data record..
        /// </summary>
        public static String deserializingSnapshot() {
            return ResourceManager.getString("DeserializingSnapshot", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered DB provider factory settings for &apos;{0}&apos;, using &apos;{1}&apos;..
        /// </summary>
        public static String discoveredConnectionProvider() {
            return ResourceManager.getString("DiscoveredConnectionProvider", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovering connection settings for &apos;{0}&apos;..
        /// </summary>
        public static String discoveringConnectionSettings() {
                return ResourceManager.getString("DiscoveringConnectionSettings", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposing underlying thread-scoped resource..
        /// </summary>
        public static String disposingRootThreadScopeResources() {
            return ResourceManager.getString("DisposingRootThreadScopeResources", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposing SQL statement resources, including any transactions and connections..
        /// </summary>
        public static String disposingStatement() {
            return ResourceManager.getString("DisposingStatement", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposing threaded scope; scope is root: {0}.
        /// </summary>
        public static String disposingThreadScope() {
            get {
                return ResourceManager.getString("DisposingThreadScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate commit detected; throwing..
        /// </summary>
        public static String duplicateCommit() {
            get {
                return ResourceManager.getString("DuplicateCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedding sharding key into connection string for &apos;{0}&apos;..
        /// </summary>
        public static String embeddingShardKey() {
            get {
                return ResourceManager.getString("EmbeddingShardKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerated {0} rows, re-querying for next page..
        /// </summary>
        public static String enumeratedRowCount() {
            get {
                return ResourceManager.getString("EnumeratedRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration of paged results threw exception of type &apos;{0}&apos;..
        /// </summary>
        public static String enumerationThrewException() {
            get {
                return ResourceManager.getString("EnumerationThrewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed statement threw an exception, but the exception was suppressed..
        /// </summary>
        public static String exceptionSuppressed() {
            get {
                return ResourceManager.getString("ExceptionSuppressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing command..
        /// </summary>
        public static String executingCommand() {
            get {
                return ResourceManager.getString("ExecutingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing query..
        /// </summary>
        public static String executingQuery() {
            get {
                return ResourceManager.getString("ExecutingQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting all commits for stream &apos;{0}&apos; between revisions &apos;{1}&apos; and &apos;{2}&apos;..
        /// </summary>
        public static String gettingAllCommitsBetween() {
            get {
                return ResourceManager.getString("GettingAllCommitsBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting all commits from &apos;{0}&apos; forward..
        /// </summary>
        public static String gettingAllCommitsFrom() {
            get {
                return ResourceManager.getString("GettingAllCommitsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting snapshot for stream &apos;{0}&apos; on or before revision {1}..
        /// </summary>
        public static String GettingRevision {
            get {
                return ResourceManager.getString("GettingRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting a list of streams to snapshot..
        /// </summary>
        public static String GettingStreamsToSnapshot {
            get {
                return ResourceManager.getString("GettingStreamsToSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting the list of all undispatched commits..
        /// </summary>
        public static String GettingUndispatchedCommits {
            get {
                return ResourceManager.getString("GettingUndispatchedCommits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing storage engine..
        /// </summary>
        public static String InitializingStorage {
            get {
                return ResourceManager.getString("InitializingStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking commit &apos;{0}&apos; as dispatched..
        /// </summary>
        public static String markingCommitAsDispatched() {
            get {
                return ResourceManager.getString("MarkingCommitAsDispatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing query with max page size of {0}..
        /// </summary>
        public static String maxPageSize() {
            get {
                return ResourceManager.getString("MaxPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the required attribute &apos;connection string&apos; on the connection name &apos;{0}&apos; in the configuration file..
        /// </summary>
        public static String missingConnectionString() {
            get {
                return ResourceManager.getString("MissingConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the required attribute &apos;providerName&apos; on the connection name &apos;{0}&apos; in the configuration file..
        /// </summary>
        public static String missingProviderName() {
            get {
                return ResourceManager.getString("MissingProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connections have been opened yet..
        /// </summary>
        public static String notConnectionsAvailable() {
            get {
                return ResourceManager.getString("NotConnectionsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object has been disposed and cannot be used..
        /// </summary>
        public static String objectAlreadyDisposed() {
            get {
                return ResourceManager.getString("ObjectAlreadyDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open connection &apos;{0}&apos;..
        /// </summary>
        public static String openFailed() {
            return ResourceManager.getString("OpenFailed", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening connection &apos;{0}&apos;..
        /// </summary>
        public static String openingConnection() {
            get {
                return ResourceManager.getString("OpeningConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening master connection &apos;{0}&apos;.
        /// </summary>
        public static String openingMasterConnection() {
            get {
                return ResourceManager.getString("OpeningMasterConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening replica connection &apos;{0}&apos;..
        /// </summary>
        public static String openingReplicaConnection() {
            get {
                return ResourceManager.getString("OpeningReplicaConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening new threaded scope for key &apos;{0}&apos;; scope is root: {1}.
        /// </summary>
        public static String openingThreadScope() {
            get {
                return ResourceManager.getString("OpeningThreadScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purging all stored data..
        /// </summary>
        public static String purgingStorage() {
            get {
                return ResourceManager.getString("PurgingStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration of result set completed, completing associated transaction scope..
        /// </summary>
        public static String queryCompleted() {
            get {
                return ResourceManager.getString("QueryCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception is recoverable, completing scope..
        /// </summary>
        public static String recoverableExceptionCompletesScope() {
            get {
                return ResourceManager.getString("RecoverableExceptionCompletesScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down persistence..
        /// </summary>
        public static String shuttingDownPersistence() {
            get {
                return ResourceManager.getString("ShuttingDownPersistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage threw exception of type &apos;{0}&apos;, wrapping and re-throwing..
        /// </summary>
        public static String storageThrewException() {
            get {
                return ResourceManager.getString("StorageThrewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participating in connection with ambient transaction scope of .
        /// </summary>
        public static String usingScope() {
            get {
                return ResourceManager.getString("UsingScope", resourceCulture);
            }
        }
    }
}
